platform :ios, "6.0"
source 'https://github.com/CocoaPods/Specs.git'


pod 'AFNetworking', '~> 2.4'
pod 'ReactiveCocoa', '~> 2.3'
pod 'Masonry', '~> 0.5'
pod 'MMDrawerController', '~> 0.5'
pod 'SDWebImage', '~> 3.7'
pod 'SWTableViewCell', '~> 0.3'
pod 'MBProgressHUD', '~> 0.9'
pod 'CHTCollectionViewWaterfallLayout'



